steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hidro-backend', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy hidro-backend \
          --image gcr.io/$PROJECT_ID/hidro-backend \
          --region southamerica-east1 \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances=$PROJECT_ID:southamerica-east1:hidrometros-instance \
          --set-secrets="DB_PASSWORD=db-password:latest,JWT_SECRET=jwt-secret:latest,/etc/secrets/google-credentials.json=google-credentials:latest" \
          --set-env-vars="DB_HOST=127.0.0.1,DB_USER=root,DB_NAME=hidrometros_db,INSTANCE_CONNECTION_NAME=$PROJECT_ID:southamerica-east1:hidrometros-instance"

images:
  - gcr.io/$PROJECT_ID/hidro-backend

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
      env: DB_PASSWORD
    - versionName: projects/$PROJECT_ID/secrets/jwt-secret/versions/latest
      env: JWT_SECRET
    - versionName: projects/$PROJECT_ID/secrets/google-credentials/versions/latest
      env: GOOGLE_APPLICATION_CREDENTIALS_JSON

options:
  logging: CLOUD_LOGGING_ONLY
