steps:
  # 1) Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/hidro-backend'
      - '.'

  # 2) Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    # Disponibiliza a variável de ambiente DB_PASSWORD para este passo
    secretEnv: ['DB_PASSWORD']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy hidro-backend \
          --image gcr.io/$PROJECT_ID/hidro-backend \
          --region southamerica-east1 \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances=$PROJECT_ID:southamerica-east1:hidrometros-instance \
          # Esta flag já configura os segredos para o serviço final no Cloud Run.
          # Não depende da seção 'availableSecrets'.
          --set-secrets="/etc/secrets/google-credentials.json=google-credentials:latest,JWT_SECRET=jwt-secret:latest" \
          # A senha do banco é passada aqui usando a variável $$DB_PASSWORD, 
          # que é populada pela seção 'availableSecrets' abaixo.
          --set-env-vars="DB_HOST=127.0.0.1,DB_USER=root,DB_PASSWORD=$$DB_PASSWORD,DB_NAME=hidrometros_db,INSTANCE_CONNECTION_NAME=$PROJECT_ID:southamerica-east1:hidrometros-instance"

images:
  - 'gcr.io/$PROJECT_ID/hidro-backend'

# A seção 'availableSecrets' é usada para expor segredos como variáveis de ambiente
# para os passos da build.
availableSecrets:
  secretManager:
    # Precisamos apenas do segredo da senha do banco aqui.
    # Certifique-se de que o nome do segredo ('db-password') está correto.
    - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
      env: 'DB_PASSWORD'