steps:
  # 1) Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/hidro-backend
      - .

  # 2) Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy hidro-backend \
          --image gcr.io/$PROJECT_ID/hidro-backend \
          --region southamerica-east1 \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances=$PROJECT_ID:southamerica-east1:hidrometros-instance \
          --set-secrets="/etc/secrets/google-credentials.json=google-credentials:latest,JWT_SECRET=jwt-secret:latest" \
          --set-env-vars="DB_HOST=127.0.0.1,DB_USER=root,DB_PASSWORD=$DB_PASSWORD,DB_NAME=hidrometros_db,INSTANCE_CONNECTION_NAME=$PROJECT_ID:southamerica-east1:hidrometros-instance"

# Imagem que queremos armazenar no Container Registry
images:
  - 'gcr.io/$PROJECT_ID/hidro-backend'
  
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/jwt-secret/versions/latest
      env: JWT_SECRET
    - versionName: projects/$PROJECT_ID/secrets/google-credentials/versions/latest
      file: google-credentials.json