steps:
  # 1) Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hidro-backend', '.']

  # 2) Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['DB_PASSWORD']
    args:
      - '-c'
      - |
        gcloud run deploy hidro-backend \
          --image gcr.io/$PROJECT_ID/hidro-backend \
          --region southamerica-east1 \
          --platform managed \
          --allow-unauthenticated \
          --add-cloudsql-instances=$PROJECT_ID:us-central1:hidrometros-instance \
          --set-secrets="/etc/secrets/google-credentials.json=google-credentials:latest" \
          --set-env-vars="DB_USER=root,DB_PASSWORD=$$DB_PASSWORD,DB_NAME=hidrometros_db,INSTANCE_CONNECTION_NAME=$PROJECT_ID:us-central1:hidrometros-instance,DB_HOST=127.0.0.1"

images:
  - 'gcr.io/$PROJECT_ID/hidro-backend'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
      env: DB_PASSWORD

options:
  logging: CLOUD_LOGGING_ONLY
